### ISSUE TITLE
UrbanSim Simulation Framework

### ISSUE THREAD

**Issue by rmbw51** [UDST/user_meeting_2014#1]
In the Synthicity 2014 User Meeting UrbanSim Simulation Framework
the
   import urbansim.sim.simulation as sim
fails because there is no "simulation" in urbansim (I have downloaded and isntalled the last version)...
any suggestion or ideas?
Thanks

**Comment by janowicz** [comment]
Hi @rmbw51, the code in the 2014 User Meeting repo is a bit outdated.  `urbansim.sim.simulation` is now `orca`.   Please see https://github.com/udst/orca.  In many cases the `@sim` decorators can be replaced with `@orca`, but there are other differences too-   I'd suggest taking a look at the orca documentation for information on the latest simulation framework.

**Comment by rmbw51** [comment]
ok, thanks,
